### ISSUE TITLE
features reduce and evaluation

### ISSUE THREAD

**Issue by kingvision** [AlfredXiangWu/face_verification_experiment#13]
HI:
   Thanks you for your replying.
   I read your paper and code. i have two questions:g
  one:  why do not you reduce the features ?  for example ,  when we get the 256 D features, we can    use PCA to reduce the features.

   two:  i do not understand that  why you use the vlfeat. i know that you use the caffe_ftr.py to extract features and use the matlab to get the cosine score. i think that if the cosine score greater than a certain threshold, then a same face. why do not you use the joint Bayesian?

thanks

**Comment by AlfredXiangWu** [comment]
1. In my opinion, 256-d isn't a pretty high-dimensional feature to represent face image, therefore, I don't use PCA or other method to do dimension reduction.
2. I use vlfeat just to evaluate the results because the vl_pr function can compute the eer for face verification evaluation results. Certainly, you can realize the evaluation code by yourself.
3. I have tried to use Joint Bayesian for my features, but it doesn't work due to the overfitting.
