### ISSUE TITLE
Model B and Model C belong to CNN-9 architecture？

### ISSUE THREAD

**Issue by VivienFu** [AlfredXiangWu/face_verification_experiment#141]
There is a CNN-29 in the paper, but I found it's quite different with Model C here, bcz there is no layers like Conv2_x. It seems both Model B and C belong to CNN-9, right? the only different of B and C is the  training datasets, is it right?

**Comment by AlfredXiangWu** [comment]
Yes, both B and C model are the Light CNN-9. The difference between B and C model is trained on different training dataset. 

About Light CNN-29 model, maybe I will release it a few month later. 

By the way, if you are trying to reproduce the model, especially Light CNN-29, I strongly recommend  you to train the model by pytorch, because the convergence is more stable and performance is much higher training by pytorch than caffe.

**Comment by yudie433** [comment]
If I training Light CNN-29 by pytorch,can I then transform the pytorch model to caffe model ?
Have you trained the Light CNN-29 by caffe，if you have , can you please share me the .caffemodel file?
Thank you very much!
