### ISSUE TITLE
Open set protocols for identification testing

### ISSUE THREAD

**Issue by yxu0611** [AlfredXiangWu/face_verification_experiment#49]
Hi,  Wu.

In your paper "A lighten CNN for deep face representation", When you do open set identification testing, as for gallery set, you use 3143 images of 596 identities, why not follow standard rule: 596 subjects with a single face image per subject? 
I tested your model B in this rule, got 59.63% (DIR@FAR=1%), I am not sure the result is correct or not.

As for VGG result in your paper, I think the verification result which you did not cite correctly in the VGG paper. You should cite accuracy not 100%-EER.
Also, do you test VGG model for close/open set for identification yourself?

Thank you.

**Comment by AlfredXiangWu** [comment]
1. I don't know which protocols you followed. I use the close-set and open-set protocols which are the same as facebook's work. The protocols is proposed by [1] and you can contact Lacey Best-Rowden or Hu Han about the details. 
2. Due to the released model by VGG, I evaluated the released model performance rather than only cited the accuracy in their paper. The open-set and close-set performance of VGG model is also mentioned in my paper. 

[1]. Lacey Best-Rowden, Hu Han, Charles Otto, Brendan Klare, Anil K. Jain: Unconstrained Face Recognition: Identifying a Person of Interest From a Media Collection. IEEE Trans. Information Forensics and Security 9(12): 2144-2157 (2014)

**Comment by yxu0611** [comment]
Hi, Wu

Thank you very much for your reply.

I only focus on open set identification protocol on LFW.
In facebook's paper[1], for open set identification, it mentions "The gallery includes 596 identities, each  with a single example" in page 6. 
But in your paper[2], you mention "the gallery set includes 3143 images of 596 identities" in page 6. There is a much different, because facebook's protocol is more difficult. So, I am confused which protocol did you follow when you test your lighten CNN in LFW dataset?
I used facebook's protocol for identification, the accuracy is 59.63% (DIR@FAR=1%). But used your protocol, the accuracy is 66.10% (DIR@FAR=1%). still have 3% gap from your paper. I use your code to generate LFW patch, but use a newer caffe version to test. 

[1] Web-Scale Training for Face Identification
[2] A Lighten CNN for Deep Face Representation

**Comment by saeedizadi** [comment]
@yxu0611 Hi, 
It's about two weeks that I'm trying to reproduce the results reported in the paper for openset identification. I don't know why my results are lower than the reported one. I think it might be due to my evaluation implementation. Would you please share the source of your impl. for computing DIR@FAR with me? Thanks

**Comment by HanHuCAS** [comment]
@yxu0611 In the open set protocol defined in [r1], the gallery set can be used in 3 different modes:  (1) one gallery image per subject; (2) multiple gallery image per subject; and (3) gallery image +gallery video per subject. This means that you should do the comparisons under the same mode of gallery.

[r1] Lacey Best-Rowden, Hu Han, Charles Otto, Brendan Klare, Anil K. Jain: Unconstrained Face Recognition: Identifying a Person of Interest From a Media Collection. IEEE Trans. Information Forensics and Security 9(12): 2144-2157 (2014)

**Comment by yxu0611** [comment]
@HanHuCAS Thanks.
