### ISSUE TITLE
Detailed in testing about mirror

### ISSUE THREAD

**Issue by rexnxiaobai** [AlfredXiangWu/face_verification_experiment#94]
dear wu,
 "To improve the robustness of our algorithm, we extract the features for each image and its horizontal mirror one, and then......"
  may you please tell me the details  about how to build the “mirror features" in megaface test.  gallery set, probe set or train set, which set did you use to train the PCA.

  Also, did you try this operation on lfw test?

**Comment by AlfredXiangWu** [comment]
We only do horizontal mirror for all the images in MegaFace and extract features. The operation is the same as the data augmentation "mirror" in caffe. Then we obtain 512(256*2) dimensional features which simply combine original features and mirror features. Finally, the 512-d features are used for evaluation on MegaFace. The operation is used to overcome landmark detection errors for MegaFace. 

Moreover, PCA is not used. And I don't try this trick on lfw because the landmarks of lfw are manually fixed by myself. I think it may not significantly improve the accuracy of lfw.

**Comment by rexnxiaobai** [comment]
very clear， thank you~
